export const loadMafiaPage = () => import('./pages/MafiaPage.vue')
export const loadNadleStreamPage = () => import('./pages/NadleStreamPage.vue')
export const loadEatFirstPage = () => import('./pages/EatFirstPage.vue')
export const loadCheckersPage = () => import('./features/checkers/pages/CheckersPage.vue')
export const loadDurakPage = () => import('./features/durak/pages/DurakPage.vue')
