version: "3.9"

services:
  server:
    build: ../apps/server
    container_name: mediasoup-server
    ports:
      - "3000:3000"
      - "40000-49999:40000-49999/udp"
    volumes:
      - ../apps/server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
