/**
 * Reusable mediasoup/WebRTC call stack. Prefer `useCallOrchestrator()` from app code (facade);
 * use `useCallEngine()` when composing inside this package or for tests. Submodules are for custom compositions.
 */
export { useCallEngine, } from './useCallEngine';
export { useCallOrchestrator } from './useCallOrchestrator';
export { SCREEN_SHARE_GET_DISPLAY_MEDIA, useCallScreenShare, useScreenShare, } from './screenShare/useCallScreenShare';
export { localPreviewStreamForOutbound } from './screenShare/previewStream';
export { useCallSessionStore } from './stores/callSession';
export { initAudioPlaybackUnlock, isAudioPlaybackUnlocked, playAllPageAudio, playAllPageAudioThrottled, registerAudioUnlockHook, } from './audio/audioPlaybackUnlock';
export { getAudioAnalysisAudioContext } from './audio/audioAnalysisContext';
export { useActiveSpeaker } from './audio/useActiveSpeaker';
export { applyOutgoingCallMicCaptureConstraints, loadCallNoiseSuppressionPreference, mergeCallOutgoingMicAudioCaptureConstraints, saveCallNoiseSuppressionPreference, } from './audio/noiseSuppressionPreference';
export { allowCallAudioQaStorageOverrides, isCallAudioQaToolsViteEnabled, } from './audio/callAudioQaGate';
export { CALL_AUDIO_DEV_DIAGNOSTICS_STORAGE_KEY, buildCallAudioDevMicSnapshot, isCallAudioDevDiagnosticsEnabled, logCallAudioDevDiagnostics, } from './audio/callAudioDevDiagnostics';
export { CALL_AUDIO_OPUS_DTX_ENABLED, resolveCallOutboundOpusDtxForProduce } from './audio/callOutboundOpusPolicy';
export { applyWebcamContentHint, DEFAULT_CALL_AUDIO_CONSTRAINTS, DEFAULT_CALL_VIDEO_CONSTRAINTS, getVideoConstraintsForPreset, } from './media/defaultMediaConstraints';
export { useLocalMedia } from './media/useLocalMedia';
export { gridSizeTierFromParticipantCount } from './media/gridTier';
export { mergeProducerLists } from './media/mergeProducerLists';
export { buildCallParticipantMap, guestDisplayNameForPeerId, mapTilesToParticipants, resolveParticipantDisplayName, } from './utils/participantsMapper';
export { buildDisplayNameUiMap, resolvePeerDisplayNameForUi, } from './utils/resolvePeerDisplayName';
export { normalizeDisplayName } from './utils/normalizeDisplayName';
export { ACTIVE_CAMERA_SMALL_ROOM_MAX, AUTO_LARGE_ROOM_SIMULCAST, AUTO_LARGE_ROOM_VIDEO_CAPTURE, AUTO_SMALL_ROOM_VIDEO_CAPTURE, countActiveCameraPublishersAtWire, getCallVideoConstraints, getSimulcastEncodingsForPreset, getSingleLayerEncodingsForPreset, isVideoQualityPreset, resolveOutgoingVideoPublishTier, resolveVideoPublishTier, VIDEO_PRESET_FALLBACK, VIDEO_PRESET_MAFIA, VIDEO_QUALITY_PRESETS, } from './media/videoQualityPreset';
export { shouldUseVideoSimulcastForRoom, spatialLayerForGridSizeTier, VIDEO_SIMULCAST_MIN_PEERS_IN_ROOM, VP8_SIMULCAST_ENCODINGS, VP8_SINGLE_LAYER_ENCODING, } from './media/videoSimulcast';
export { ENABLE_PUBLISHER_SIMULCAST, ENABLE_RECEIVER_ADAPTIVE_LAYERS, SIMULCAST_ACTIVE_CAMERA_THRESHOLD, } from './media/adaptiveSimulcastFeatureFlags';
export { layerAtOrBelow, profileFloorCeiling, resolveInitialBaselineLayer, resolveReceiverBaselineLayer, simulcastLayersForBaseline, stepDownLayer, stepUpLayer, } from './media/receiverBaselineLayerPolicy';
export { assignAdaptivePreferredLayersByPeerId, MAX_HIGH_STREAMS, MAX_MEDIUM_STREAMS, } from './media/adaptiveVideoPreferredLayers';
export { readNavigatorDeviceProfileInput, resolveReceiveDeviceProfile, RECEIVE_DEVICE_DEFAULT_MAX_HIGH, RECEIVE_DEVICE_DEFAULT_MAX_MEDIUM, } from './media/receiveDeviceProfile';
export { applyReceiveQualityPressureToLayers, } from './media/receiveVideoQualityPressure';
export { advancePlaybackRenderFpsPressureByPeer, aggregateInboundVideoStatsByPeerId, applyFpsRenderPressure, evaluateInboundFpsRenderPressure, FPS_RENDER_PRESSURE_BAD_STREAK_DOWN, FPS_RENDER_PRESSURE_GOOD_STREAK_UP, FPS_RENDER_PRESSURE_MIN_FPS, } from './media/videoFpsPressure';
export { useMediasoupDevice } from './media/useMediasoupDevice';
export { useRemoteMedia, } from './media/useRemoteMedia';
export { loadRemoteListeningPrefs, saveRemoteListeningPrefs } from './audio/remoteListeningPrefs';
export { useRoomConnection, } from './signaling/useRoomConnection';
export { parseProducerSyncPayload } from './signaling/producerSyncPayload';
export { useSendTransport, } from './transport/useSendTransport';
export { waitForCondition } from './utils/waitForCondition';
export { tryConsumeProducerOnce } from './utils/consumerDedup';
export { newCallTabPeerId, readOrCreateCallDeviceId } from './utils/callTabPeerId';
export { replyJsonPingIfNeeded } from './utils/jsonWsPing';
